import{a as E,S as R,i}from"./assets/vendor-Bt_EzQve.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const f of s.addedNodes)f.tagName==="LINK"&&f.rel==="modulepreload"&&a(f)}).observe(document,{childList:!0,subtree:!0});function e(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function a(t){if(t.ep)return;t.ep=!0;const s=e(t);fetch(t.href,s)}})();const q="https://pixabay.com/api/",P="53018181-d15c82787ceb9d2a9f401c449";async function m(o,r=1){const e={key:P,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:r};try{return(await E.get(q,{params:e})).data}catch(a){throw console.error("Error fetching images:",a),a}}const y=document.querySelector(".gallery"),L=document.querySelector(".loader"),l=document.querySelector(".load-more"),$=new R(".gallery a",{captionsData:"alt",captionDelay:250,captionPosition:"bottom"});function w(o){const r=o.map(e=>`
      <li class="gallery-item">
        <a href="${e.largeImageURL}">
          <img src="${e.webformatURL}" alt="${e.tags}" />
        </a>
        <div class="stats">
          <p> ${e.likes}</p>
          <p> ${e.views}</p>
          <p> ${e.comments}</p>
          <p>⬇ ${e.downloads}</p>
        </div>
      </li>`).join("");y.insertAdjacentHTML("beforeend",r),$.refresh()}function B(){y.innerHTML=""}function b(){L.classList.remove("hidden")}function d(){L.classList.add("hidden")}function v(){l&&l.classList.remove("hidden")}function u(){l&&l.classList.add("hidden")}const h=document.querySelector(".form"),H=h.elements["search-text"],p=document.querySelector(".load-more"),M=document.querySelector(".gallery");let c="",n=1;const S=15;let g=0;h.addEventListener("submit",async o=>{o.preventDefault();const r=H.value.trim();if(!r){i.warning({title:"Warning",message:"Please enter a search term!",position:"topRight"});return}r!==c&&(c=r,n=1,B(),u()),b();try{const e=await m(c,n);if(d(),!e.hits||e.hits.length===0){i.info({title:"No results",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}n===1&&i.success({title:"Found",message:`Hooray! We found ${e.totalHits} images.`,position:"topRight"}),w(e.hits),g=e.totalHits,n*S<g?v():(u(),n>1&&i.info({title:"End",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch{d(),i.error({title:"Error",message:"Something went wrong while fetching images.",position:"topRight"})}finally{h.reset()}});p&&p.addEventListener("click",async()=>{if(c){n+=1,b();try{const o=await m(c,n);if(d(),!o.hits||o.hits.length===0){u(),i.info({title:"End",message:"We're sorry, but you've reached the end of search results.",position:"topRight"});return}w(o.hits);const r=M.querySelector(".gallery-item");if(r){const{height:e}=r.getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}n*S>=o.totalHits?(u(),i.info({title:"End",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):v()}catch{d(),i.error({title:"Error",message:"Something went wrong while loading more images.",position:"topRight"})}}});
//# sourceMappingURL=index.js.map
